### ISSUE TITLE
Snek roadmap

### ISSUE THREAD

**Issue by MCWertGaming** [BlackVyperStudios/snek#10]
This is our roadmap for snek. The features are intended to be finished in their versions, but that doe not mean that smaller things can't be worked on earlier.

Version 1.0.X - The start
- [ ] replace ncurses with cpp-terminal
- [ ] add game menu
- [ ] port the snake to the new version
- [ ] add integration testing

Version 1.1.X - Testing and Fixing
- [ ] enforce clang-format for PRs
- [ ] enable compiler warnings and turn them to errors
- [ ] (add clang-tidy checking)
- [ ] add github action for updating sub-modules
- [ ] add unit testing of sneks most important pats
- [ ] switch from FOLF-namespace to foxspace
- [ ] outsource common utils to foxspace
- [ ] move to C++20s 'import'
- [ ] make cpp-terminal and foxspace use import
- [ ] merge all terminal preparing into upstream cpp-terminal

Version 2.2.X - Optimizing
- [ ] generalize Menu UI
- [ ] center the menu
- [ ] create seperate drawing thread for handling the terminal
- [ ] move to cpp-terminals window class
- [ ] add dummy message on too small screen

Version 3.X.X - Features
- [ ] add singleplayer classic mode
- [ ] add single player snek mode
- [ ] add singleplayer chaos mode
- [ ] add singleplayer infinite mode
- [ ] add singleplayer creative mode
- [ ] port game modes to local multiplayer
- [ ] add animations (menu and game)
- [ ] add highscores for singleplayer
- [ ] add online highscore
- [ ] Official theme options
- [ ] Custom theme Support
- [ ] Modding support

Version 4.X.X - Online Snek!
- [ ] Make a playable web version of snek
- [ ] Make GUI version of snek
- [ ] create localhost / local lan online play
- [ ] create official online server
- [ ] add server browser
- [ ] create dedicated server
- [ ] add unofficial server browser
- [ ] add private server connect
- [ ] add anticheat to official snek
- [ ] add the option to only allow certain clients on online servers

Version 5.X.X - Snek Escallation
- [ ] Snek50 (Snake online but you against 49 other players)
- [ ] Snek50 Teams (Snek online but 20 vs 20 vs 20 people in three teams)
- [ ] Events

**Comment by mattcoding4days** [comment]
Can you open a projects board here on github, or Zen hub integration, so issues/tasks and progress can be easily seen by contributors, it helps see what is in progress, what is backlogged etc

**Comment by MCWertGaming** [comment]
Sure! I'm planing on moving all tasks to a GitHub projects board. Will get to that after this project is ready for public contributions. We have to do some clean up and want to move to another Terminal library to support things like themes.
